In [22]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt

# Import the data into Pandas dataframe
data = pd.read_csv("API_testing_project.csv")

In [23]:
data.head()

,test_id,category,source,target,input,expected_behavior,actual_output,result,http_status,response_time_ms,notes
0,1,Basic translation,EN,ES,"""How are you?""",¿Cómo estás?,¿Cómo estás?,PASS,200 OK,2250,NaN
1,2,Basic translation,EN,FR,"""How are you?""","""Comment ça va ?""","""Comment ça va ?""",PASS,200 OK,3070,NaN
2,3,Unicode characters,ES,EN,"""¿Cuándo saldrá la película? ¡Me emociono!""","""When will the movie come out? I'm excited!""","""When will the movie come out? I'm excited!""",PASS,200 OK,1640,NaN
3,4,Idiomatic expressions,ES,EN,"""Va a llover a cántaros.""",It's raining cats and dogs.,It's raining cats and dogs.,PASS,200 OK,2370,NaN
4,5,Ambiguous word/context,ES,EN,"""Me senté en el banco, y luego deposité dinero...","""I sat on the bench, and then deposited money ...","""I sat on the bench, and then deposited money ...",PASS,200 OK,2630,Repeated requests demonstrate two possible out...

In [24]:
data["result"].value_counts(normalize=True)

result
PASS    0.875
FAIL    0.125
Name: proportion, dtype: float64

In [25]:
data[data["result"] == "FAIL"]

,test_id,category,source,target,input,expected_behavior,actual_output,result,http_status,response_time_ms,notes
7,8,Invalid source language - unsupported,not_a_real_language_12345,ES,"""This is silly.""","""translation"": ""Unsupported language code or u...","""source"": ""not_a_real_language_12345"",\n""targe...",FAIL,200 OK,1810,"Testing with ""source: Klingon"" reveals Klingon..."

In [27]:
avg_response_time = round(data["response_time_ms"].mean(), 2)

print(f"Average API response time: {avg_response_time} milliseconds")

Average API response time: 1942.88 milliseconds

In [40]:
tests_valid = data[data["result"] == "PASS"]

avg_time_valid = round(tests_valid["response_time_ms"].mean(), 2)

print(f"Average API reponse time among valid test cases: {avg_time_valid}")

Average API reponse time among valid test cases: 1961.86

In [ ]:
# Fastest and slowest response times
fastest = min(data["response_time_ms"])
slowest = max(data["response_time_ms"])

print(f"Fastest time: {fastest}")
print(f"Slowest time: {slowest}")

Fastest time: 313
Slowest time: 3070

In [58]:
# Fastest response
fastest_test = data.loc[data["response_time_ms"] == fastest, "category"].iloc[0]
slowest_test = data.loc[data["response_time_ms"] == slowest, "category"].iloc[0]

print(f"Fastest test: {fastest_test}")
print(f"Slowest test: {slowest_test}")

Fastest test: Empty input
Slowest test: Basic translation

In [74]:
# Average response time per category?

avg_res_time = data.groupby(["category"])["response_time_ms"].mean()
avg_res_time

category
Ambiguous word/context                   2630.0
Basic translation                        2660.0
Code-switching                           1460.0
Empty input                               313.0
Idiomatic expressions                    2370.0
Invalid source language - unsupported    1810.0
Unicode characters                       1640.0
Name: response_time_ms, dtype: float64